import type { StationPatternEntry } from './models';

export const STATION_PATTERNS: readonly StationPatternEntry[] = [
  // --- OH（小田原線）---
  {
    label: '新宿',
    line: 'OH',
    name: { kanji: '新宿', hiragana: 'しんじゅく', romaji: 'Shinjuku' },
    prev: { kanji: '', romaji: '' },
    next: { kanji: '南新宿', romaji: 'Minami-Shinjuku' },
    currentNumbering: { symbol: 'OH', number: '01' },
    nextNumbering: { symbol: 'OH', number: '02' },
  },
  {
    label: '南新宿',
    line: 'OH',
    name: { kanji: '南新宿', hiragana: 'みなみしんじゅく', romaji: 'Minami-Shinjuku' },
    prev: { kanji: '新宿', romaji: 'Shinjuku' },
    next: { kanji: '参宮橋', romaji: 'Sangubashi' },
    currentNumbering: { symbol: 'OH', number: '02' },
    nextNumbering: { symbol: 'OH', number: '03' },
  },
  {
    label: '参宮橋',
    line: 'OH',
    name: { kanji: '参宮橋', hiragana: 'さんぐうばし', romaji: 'Sangubashi' },
    prev: { kanji: '南新宿', romaji: 'Minami-Shinjuku' },
    next: { kanji: '代々木八幡', romaji: 'Yoyogi-Hachiman' },
    currentNumbering: { symbol: 'OH', number: '03' },
    nextNumbering: { symbol: 'OH', number: '04' },
  },
  {
    label: '代々木八幡',
    line: 'OH',
    name: { kanji: '代々木八幡', hiragana: 'よよぎはちまん', romaji: 'Yoyogi-Hachiman' },
    prev: { kanji: '参宮橋', romaji: 'Sangubashi' },
    next: { kanji: '代々木上原', romaji: 'Yoyogi-Uehara' },
    currentNumbering: { symbol: 'OH', number: '04' },
    nextNumbering: { symbol: 'OH', number: '05' },
  },
  {
    label: '代々木上原',
    line: 'OH',
    name: { kanji: '代々木上原', hiragana: 'よよぎうえはら', romaji: 'Yoyogi-Uehara' },
    prev: { kanji: '代々木八幡', romaji: 'Yoyogi-Hachiman' },
    next: { kanji: '東北沢', romaji: 'Higashi-Kitazawa' },
    currentNumbering: { symbol: 'OH', number: '05' },
    nextNumbering: { symbol: 'OH', number: '06' },
  },
  {
    label: '東北沢',
    line: 'OH',
    name: { kanji: '東北沢', hiragana: 'ひがしきたざわ', romaji: 'Higashi-Kitazawa' },
    prev: { kanji: '代々木上原', romaji: 'Yoyogi-Uehara' },
    next: { kanji: '下北沢', romaji: 'Shimo-Kitazawa' },
    currentNumbering: { symbol: 'OH', number: '06' },
    nextNumbering: { symbol: 'OH', number: '07' },
  },
  {
    label: '下北沢',
    line: 'OH',
    name: { kanji: '下北沢', hiragana: 'しもきたざわ', romaji: 'Shimo-Kitazawa' },
    prev: { kanji: '東北沢', romaji: 'Higashi-Kitazawa' },
    next: { kanji: '世田谷代田', romaji: 'Setagaya-Daita' },
    currentNumbering: { symbol: 'OH', number: '07' },
    nextNumbering: { symbol: 'OH', number: '08' },
  },
  {
    label: '世田谷代田',
    line: 'OH',
    name: { kanji: '世田谷代田', hiragana: 'せたがやだいだ', romaji: 'Setagaya-Daita' },
    prev: { kanji: '下北沢', romaji: 'Shimo-Kitazawa' },
    next: { kanji: '梅ヶ丘', romaji: 'Umegaoka' },
    currentNumbering: { symbol: 'OH', number: '08' },
    nextNumbering: { symbol: 'OH', number: '09' },
  },
  {
    label: '梅ヶ丘',
    line: 'OH',
    name: { kanji: '梅ヶ丘', hiragana: 'うめがおか', romaji: 'Umegaoka' },
    prev: { kanji: '世田谷代田', romaji: 'Setagaya-Daita' },
    next: { kanji: '豪徳寺', romaji: 'Gotokuji' },
    currentNumbering: { symbol: 'OH', number: '09' },
    nextNumbering: { symbol: 'OH', number: '10' },
  },
  {
    label: '豪徳寺',
    line: 'OH',
    name: { kanji: '豪徳寺', hiragana: 'ごうとくじ', romaji: 'Gotokuji' },
    prev: { kanji: '梅ヶ丘', romaji: 'Umegaoka' },
    next: { kanji: '経堂', romaji: 'Kyodo' },
    currentNumbering: { symbol: 'OH', number: '10' },
    nextNumbering: { symbol: 'OH', number: '11' },
  },
  {
    label: '経堂',
    line: 'OH',
    name: { kanji: '経堂', hiragana: 'きょうどう', romaji: 'Kyodo' },
    prev: { kanji: '豪徳寺', romaji: 'Gotokuji' },
    next: { kanji: '千歳船橋', romaji: 'Chitose-Funabashi' },
    currentNumbering: { symbol: 'OH', number: '11' },
    nextNumbering: { symbol: 'OH', number: '12' },
  },
  {
    label: '千歳船橋',
    line: 'OH',
    name: { kanji: '千歳船橋', hiragana: 'ちとせふなばし', romaji: 'Chitose-Funabashi' },
    prev: { kanji: '経堂', romaji: 'Kyodo' },
    next: { kanji: '祖師ヶ谷大蔵', romaji: 'Soshigaya-Okura' },
    currentNumbering: { symbol: 'OH', number: '12' },
    nextNumbering: { symbol: 'OH', number: '13' },
  },
  {
    label: '祖師ヶ谷大蔵',
    line: 'OH',
    name: { kanji: '祖師ヶ谷大蔵', hiragana: 'そしがやおおくら', romaji: 'Soshigaya-Okura' },
    prev: { kanji: '千歳船橋', romaji: 'Chitose-Funabashi' },
    next: { kanji: '成城学園前', romaji: 'Seijogakuen-mae' },
    currentNumbering: { symbol: 'OH', number: '13' },
    nextNumbering: { symbol: 'OH', number: '14' },
  },
  {
    label: '成城学園前',
    line: 'OH',
    name: { kanji: '成城学園前', hiragana: 'せいじょうがくえんまえ', romaji: 'Seijogakuen-mae' },
    prev: { kanji: '祖師ヶ谷大蔵', romaji: 'Soshigaya-Okura' },
    next: { kanji: '喜多見', romaji: 'Kitami' },
    currentNumbering: { symbol: 'OH', number: '14' },
    nextNumbering: { symbol: 'OH', number: '15' },
  },
  {
    label: '喜多見',
    line: 'OH',
    name: { kanji: '喜多見', hiragana: 'きたみ', romaji: 'Kitami' },
    prev: { kanji: '成城学園前', romaji: 'Seijogakuen-mae' },
    next: { kanji: '狛江', romaji: 'Komae' },
    currentNumbering: { symbol: 'OH', number: '15' },
    nextNumbering: { symbol: 'OH', number: '16' },
  },
  {
    label: '狛江',
    line: 'OH',
    name: { kanji: '狛江', hiragana: 'こまえ', romaji: 'Komae' },
    prev: { kanji: '喜多見', romaji: 'Kitami' },
    next: { kanji: '和泉多摩川', romaji: 'Izumi-Tamagawa' },
    currentNumbering: { symbol: 'OH', number: '16' },
    nextNumbering: { symbol: 'OH', number: '17' },
  },
  {
    label: '和泉多摩川',
    line: 'OH',
    name: { kanji: '和泉多摩川', hiragana: 'いずみたまがわ', romaji: 'Izumi-Tamagawa' },
    prev: { kanji: '狛江', romaji: 'Komae' },
    next: { kanji: '登戸', romaji: 'Noborito' },
    currentNumbering: { symbol: 'OH', number: '17' },
    nextNumbering: { symbol: 'OH', number: '18' },
  },
  {
    label: '登戸',
    line: 'OH',
    name: { kanji: '登戸', hiragana: 'のぼりと', romaji: 'Noborito' },
    prev: { kanji: '和泉多摩川', romaji: 'Izumi-Tamagawa' },
    next: { kanji: '向ヶ丘遊園', romaji: 'Mukogaoka-yuen' },
    currentNumbering: { symbol: 'OH', number: '18' },
    nextNumbering: { symbol: 'OH', number: '19' },
  },
  {
    label: '向ヶ丘遊園',
    line: 'OH',
    name: { kanji: '向ヶ丘遊園', hiragana: 'むこうがおかゆうえん', romaji: 'Mukogaoka-yuen' },
    prev: { kanji: '登戸', romaji: 'Noborito' },
    next: { kanji: '生田', romaji: 'Ikuta' },
    currentNumbering: { symbol: 'OH', number: '19' },
    nextNumbering: { symbol: 'OH', number: '20' },
  },
  {
    label: '生田',
    line: 'OH',
    name: { kanji: '生田', hiragana: 'いくた', romaji: 'Ikuta' },
    prev: { kanji: '向ヶ丘遊園', romaji: 'Mukogaoka-yuen' },
    next: { kanji: '読売ランド前', romaji: 'Yomiuri-Land-mae' },
    currentNumbering: { symbol: 'OH', number: '20' },
    nextNumbering: { symbol: 'OH', number: '21' },
  },
  {
    label: '読売ランド前',
    line: 'OH',
    name: { kanji: '読売ランド前', hiragana: 'よみうりランドまえ', romaji: 'Yomiuri-Land-mae' },
    prev: { kanji: '生田', romaji: 'Ikuta' },
    next: { kanji: '百合ヶ丘', romaji: 'Yurigaoka' },
    currentNumbering: { symbol: 'OH', number: '21' },
    nextNumbering: { symbol: 'OH', number: '22' },
  },
  {
    label: '百合ヶ丘',
    line: 'OH',
    name: { kanji: '百合ヶ丘', hiragana: 'ゆりがおか', romaji: 'Yurigaoka' },
    prev: { kanji: '読売ランド前', romaji: 'Yomiuri-Land-mae' },
    next: { kanji: '新百合ヶ丘', romaji: 'Shin-Yurigaoka' },
    currentNumbering: { symbol: 'OH', number: '22' },
    nextNumbering: { symbol: 'OH', number: '23' },
  },
  {
    label: '新百合ヶ丘',
    line: 'OH',
    name: { kanji: '新百合ヶ丘', hiragana: 'しんゆりがおか', romaji: 'Shin-Yurigaoka' },
    prev: { kanji: '百合ヶ丘', romaji: 'Yurigaoka' },
    next: { kanji: '柿生', romaji: 'Kakio' },
    currentNumbering: { symbol: 'OH', number: '23' },
    nextNumbering: { symbol: 'OH', number: '24' },
  },
  {
    label: '柿生',
    line: 'OH',
    name: { kanji: '柿生', hiragana: 'かきお', romaji: 'Kakio' },
    prev: { kanji: '新百合ヶ丘', romaji: 'Shin-Yurigaoka' },
    next: { kanji: '鶴川', romaji: 'Tsurukawa' },
    currentNumbering: { symbol: 'OH', number: '24' },
    nextNumbering: { symbol: 'OH', number: '25' },
  },
  {
    label: '鶴川',
    line: 'OH',
    name: { kanji: '鶴川', hiragana: 'つるかわ', romaji: 'Tsurukawa' },
    prev: { kanji: '柿生', romaji: 'Kakio' },
    next: { kanji: '玉川学園前', romaji: 'Tamagawagakuen-mae' },
    currentNumbering: { symbol: 'OH', number: '25' },
    nextNumbering: { symbol: 'OH', number: '26' },
  },
  {
    label: '玉川学園前',
    line: 'OH',
    name: { kanji: '玉川学園前', hiragana: 'たまがわがくえんまえ', romaji: 'Tamagawagakuen-mae' },
    prev: { kanji: '鶴川', romaji: 'Tsurukawa' },
    next: { kanji: '町田', romaji: 'Machida' },
    currentNumbering: { symbol: 'OH', number: '26' },
    nextNumbering: { symbol: 'OH', number: '27' },
  },
  {
    label: '町田',
    line: 'OH',
    name: { kanji: '町田', hiragana: 'まちだ', romaji: 'Machida' },
    prev: { kanji: '玉川学園前', romaji: 'Tamagawagakuen-mae' },
    next: { kanji: '相模大野', romaji: 'Sagami-Ono' },
    currentNumbering: { symbol: 'OH', number: '27' },
    nextNumbering: { symbol: 'OH', number: '28' },
  },
  {
    label: '相模大野',
    line: 'OH',
    name: { kanji: '相模大野', hiragana: 'さがみおおの', romaji: 'Sagami-Ono' },
    prev: { kanji: '町田', romaji: 'Machida' },
    next: { kanji: '小田急相模原', romaji: 'Odakyu Sagamihara' },
    currentNumbering: { symbol: 'OH', number: '28' },
    nextNumbering: { symbol: 'OH', number: '29' },
  },
  {
    label: '小田急相模原',
    line: 'OH',
    name: { kanji: '小田急相模原', hiragana: 'おだきゅうさがみはら', romaji: 'Odakyu Sagamihara' },
    prev: { kanji: '相模大野', romaji: 'Sagami-Ono' },
    next: { kanji: '相武台前', romaji: 'Sobudai-mae' },
    currentNumbering: { symbol: 'OH', number: '29' },
    nextNumbering: { symbol: 'OH', number: '30' },
  },
  {
    label: '相武台前',
    line: 'OH',
    name: { kanji: '相武台前', hiragana: 'そうぶだいまえ', romaji: 'Sobudai-mae' },
    prev: { kanji: '小田急相模原', romaji: 'Odakyu Sagamihara' },
    next: { kanji: '座間', romaji: 'Zama' },
    currentNumbering: { symbol: 'OH', number: '30' },
    nextNumbering: { symbol: 'OH', number: '31' },
  },
  {
    label: '座間',
    line: 'OH',
    name: { kanji: '座間', hiragana: 'ざま', romaji: 'Zama' },
    prev: { kanji: '相武台前', romaji: 'Sobudai-mae' },
    next: { kanji: '海老名', romaji: 'Ebina' },
    currentNumbering: { symbol: 'OH', number: '31' },
    nextNumbering: { symbol: 'OH', number: '32' },
  },
  {
    label: '海老名',
    line: 'OH',
    name: { kanji: '海老名', hiragana: 'えびな', romaji: 'Ebina' },
    prev: { kanji: '座間', romaji: 'Zama' },
    next: { kanji: '厚木', romaji: 'Atsugi' },
    currentNumbering: { symbol: 'OH', number: '32' },
    nextNumbering: { symbol: 'OH', number: '33' },
  },
  {
    label: '厚木',
    line: 'OH',
    name: { kanji: '厚木', hiragana: 'あつぎ', romaji: 'Atsugi' },
    prev: { kanji: '海老名', romaji: 'Ebina' },
    next: { kanji: '本厚木', romaji: 'Hon-Atsugi' },
    currentNumbering: { symbol: 'OH', number: '33' },
    nextNumbering: { symbol: 'OH', number: '34' },
  },
  {
    label: '本厚木',
    line: 'OH',
    name: { kanji: '本厚木', hiragana: 'ほんあつぎ', romaji: 'Hon-Atsugi' },
    prev: { kanji: '厚木', romaji: 'Atsugi' },
    next: { kanji: '愛甲石田', romaji: 'Aiko-Ishida' },
    currentNumbering: { symbol: 'OH', number: '34' },
    nextNumbering: { symbol: 'OH', number: '35' },
  },
  {
    label: '愛甲石田',
    line: 'OH',
    name: { kanji: '愛甲石田', hiragana: 'あいこういしだ', romaji: 'Aiko-Ishida' },
    prev: { kanji: '本厚木', romaji: 'Hon-Atsugi' },
    next: { kanji: '伊勢原', romaji: 'Isehara' },
    currentNumbering: { symbol: 'OH', number: '35' },
    nextNumbering: { symbol: 'OH', number: '36' },
  },
  {
    label: '伊勢原',
    line: 'OH',
    name: { kanji: '伊勢原', hiragana: 'いせはら', romaji: 'Isehara' },
    prev: { kanji: '愛甲石田', romaji: 'Aiko-Ishida' },
    next: { kanji: '鶴巻温泉', romaji: 'Tsurumaki-onsen' },
    currentNumbering: { symbol: 'OH', number: '36' },
    nextNumbering: { symbol: 'OH', number: '37' },
  },
  {
    label: '鶴巻温泉',
    line: 'OH',
    name: { kanji: '鶴巻温泉', hiragana: 'つるまきおんせん', romaji: 'Tsurumaki-onsen' },
    prev: { kanji: '伊勢原', romaji: 'Isehara' },
    next: { kanji: '東海大学前', romaji: 'Tokaidaigaku-mae' },
    currentNumbering: { symbol: 'OH', number: '37' },
    nextNumbering: { symbol: 'OH', number: '38' },
  },
  {
    label: '東海大学前',
    line: 'OH',
    name: { kanji: '東海大学前', hiragana: 'とうかいだいがくまえ', romaji: 'Tokaidaigaku-mae' },
    prev: { kanji: '鶴巻温泉', romaji: 'Tsurumaki-onsen' },
    next: { kanji: '秦野', romaji: 'Hadano' },
    currentNumbering: { symbol: 'OH', number: '38' },
    nextNumbering: { symbol: 'OH', number: '39' },
  },
  {
    label: '秦野',
    line: 'OH',
    name: { kanji: '秦野', hiragana: 'はだの', romaji: 'Hadano' },
    prev: { kanji: '東海大学前', romaji: 'Tokaidaigaku-mae' },
    next: { kanji: '渋沢', romaji: 'Shibusawa' },
    currentNumbering: { symbol: 'OH', number: '39' },
    nextNumbering: { symbol: 'OH', number: '40' },
  },
  {
    label: '渋沢',
    line: 'OH',
    name: { kanji: '渋沢', hiragana: 'しぶさわ', romaji: 'Shibusawa' },
    prev: { kanji: '秦野', romaji: 'Hadano' },
    next: { kanji: '新松田', romaji: 'Shin-Matsuda' },
    currentNumbering: { symbol: 'OH', number: '40' },
    nextNumbering: { symbol: 'OH', number: '41' },
  },
  {
    label: '新松田',
    line: 'OH',
    name: { kanji: '新松田', hiragana: 'しんまつだ', romaji: 'Shin-Matsuda' },
    prev: { kanji: '渋沢', romaji: 'Shibusawa' },
    next: { kanji: '開成', romaji: 'Kaisei' },
    currentNumbering: { symbol: 'OH', number: '41' },
    nextNumbering: { symbol: 'OH', number: '42' },
  },
  {
    label: '開成',
    line: 'OH',
    name: { kanji: '開成', hiragana: 'かいせい', romaji: 'Kaisei' },
    prev: { kanji: '新松田', romaji: 'Shin-Matsuda' },
    next: { kanji: '栢山', romaji: 'Kayama' },
    currentNumbering: { symbol: 'OH', number: '42' },
    nextNumbering: { symbol: 'OH', number: '43' },
  },
  {
    label: '栢山',
    line: 'OH',
    name: { kanji: '栢山', hiragana: 'かやま', romaji: 'Kayama' },
    prev: { kanji: '開成', romaji: 'Kaisei' },
    next: { kanji: '富水', romaji: 'Tomizu' },
    currentNumbering: { symbol: 'OH', number: '43' },
    nextNumbering: { symbol: 'OH', number: '44' },
  },
  {
    label: '富水',
    line: 'OH',
    name: { kanji: '富水', hiragana: 'とみず', romaji: 'Tomizu' },
    prev: { kanji: '栢山', romaji: 'Kayama' },
    next: { kanji: '螢田', romaji: 'Hotaruda' },
    currentNumbering: { symbol: 'OH', number: '44' },
    nextNumbering: { symbol: 'OH', number: '45' },
  },
  {
    label: '螢田',
    line: 'OH',
    name: { kanji: '螢田', hiragana: 'ほたるだ', romaji: 'Hotaruda' },
    prev: { kanji: '富水', romaji: 'Tomizu' },
    next: { kanji: '足柄', romaji: 'Ashigara' },
    currentNumbering: { symbol: 'OH', number: '45' },
    nextNumbering: { symbol: 'OH', number: '46' },
  },
  {
    label: '足柄',
    line: 'OH',
    name: { kanji: '足柄', hiragana: 'あしがら', romaji: 'Ashigara' },
    prev: { kanji: '螢田', romaji: 'Hotaruda' },
    next: { kanji: '小田原', romaji: 'Odawara' },
    currentNumbering: { symbol: 'OH', number: '46' },
    nextNumbering: { symbol: 'OH', number: '47' },
  },
  {
    label: '小田原',
    line: 'OH',
    name: { kanji: '小田原', hiragana: 'おだわら', romaji: 'Odawara' },
    prev: { kanji: '足柄', romaji: 'Ashigara' },
    next: { kanji: '箱根板橋', romaji: 'Hakone-Itabashi' },
    currentNumbering: { symbol: 'OH', number: '47' },
    nextNumbering: { symbol: 'OH', number: '48' },
  },
  // --- OE（江ノ島線）---
  {
    label: '東林間',
    line: 'OE',
    name: { kanji: '東林間', hiragana: 'ひがしりんかん', romaji: 'Higashi-Rinkan' },
    prev: { kanji: '相模大野', romaji: 'Sagami-Ono' },
    next: { kanji: '中央林間', romaji: 'Chuo-Rinkan' },
    currentNumbering: { symbol: 'OE', number: '01' },
    nextNumbering: { symbol: 'OE', number: '02' },
  },
  {
    label: '中央林間',
    line: 'OE',
    name: { kanji: '中央林間', hiragana: 'ちゅうおうりんかん', romaji: 'Chuo-Rinkan' },
    prev: { kanji: '東林間', romaji: 'Higashi-Rinkan' },
    next: { kanji: '南林間', romaji: 'Minami-Rinkan' },
    currentNumbering: { symbol: 'OE', number: '02' },
    nextNumbering: { symbol: 'OE', number: '03' },
  },
  {
    label: '南林間',
    line: 'OE',
    name: { kanji: '南林間', hiragana: 'みなみりんかん', romaji: 'Minami-Rinkan' },
    prev: { kanji: '中央林間', romaji: 'Chuo-Rinkan' },
    next: { kanji: '鶴間', romaji: 'Tsuruma' },
    currentNumbering: { symbol: 'OE', number: '03' },
    nextNumbering: { symbol: 'OE', number: '04' },
  },
  {
    label: '鶴間',
    line: 'OE',
    name: { kanji: '鶴間', hiragana: 'つるま', romaji: 'Tsuruma' },
    prev: { kanji: '南林間', romaji: 'Minami-Rinkan' },
    next: { kanji: '大和', romaji: 'Yamato' },
    currentNumbering: { symbol: 'OE', number: '04' },
    nextNumbering: { symbol: 'OE', number: '05' },
  },
  {
    label: '大和',
    line: 'OE',
    name: { kanji: '大和', hiragana: 'やまと', romaji: 'Yamato' },
    prev: { kanji: '鶴間', romaji: 'Tsuruma' },
    next: { kanji: '桜ヶ丘', romaji: 'Sakuragaoka' },
    currentNumbering: { symbol: 'OE', number: '05' },
    nextNumbering: { symbol: 'OE', number: '06' },
  },
  {
    label: '桜ヶ丘',
    line: 'OE',
    name: { kanji: '桜ヶ丘', hiragana: 'さくらがおか', romaji: 'Sakuragaoka' },
    prev: { kanji: '大和', romaji: 'Yamato' },
    next: { kanji: '高座渋谷', romaji: 'Koza-Shibuya' },
    currentNumbering: { symbol: 'OE', number: '06' },
    nextNumbering: { symbol: 'OE', number: '07' },
  },
  {
    label: '高座渋谷',
    line: 'OE',
    name: { kanji: '高座渋谷', hiragana: 'こうざしぶや', romaji: 'Koza-Shibuya' },
    prev: { kanji: '桜ヶ丘', romaji: 'Sakuragaoka' },
    next: { kanji: '長後', romaji: 'Chogo' },
    currentNumbering: { symbol: 'OE', number: '07' },
    nextNumbering: { symbol: 'OE', number: '08' },
  },
  {
    label: '長後',
    line: 'OE',
    name: { kanji: '長後', hiragana: 'ちょうご', romaji: 'Chogo' },
    prev: { kanji: '高座渋谷', romaji: 'Koza-Shibuya' },
    next: { kanji: '湘南台', romaji: 'Shonandai' },
    currentNumbering: { symbol: 'OE', number: '08' },
    nextNumbering: { symbol: 'OE', number: '09' },
  },
  {
    label: '湘南台',
    line: 'OE',
    name: { kanji: '湘南台', hiragana: 'しょうなんだい', romaji: 'Shonandai' },
    prev: { kanji: '長後', romaji: 'Chogo' },
    next: { kanji: '六会日大前', romaji: 'Mutsuai-Nichidai-mae' },
    currentNumbering: { symbol: 'OE', number: '09' },
    nextNumbering: { symbol: 'OE', number: '10' },
  },
  {
    label: '六会日大前',
    line: 'OE',
    name: { kanji: '六会日大前', hiragana: 'むつあいにちだいまえ', romaji: 'Mutsuai-Nichidai-mae' },
    prev: { kanji: '湘南台', romaji: 'Shonandai' },
    next: { kanji: '善行', romaji: 'Zengyo' },
    currentNumbering: { symbol: 'OE', number: '10' },
    nextNumbering: { symbol: 'OE', number: '11' },
  },
  {
    label: '善行',
    line: 'OE',
    name: { kanji: '善行', hiragana: 'ぜんぎょう', romaji: 'Zengyo' },
    prev: { kanji: '六会日大前', romaji: 'Mutsuai-Nichidai-mae' },
    next: { kanji: '藤沢本町', romaji: 'Fujisawa-hommachi' },
    currentNumbering: { symbol: 'OE', number: '11' },
    nextNumbering: { symbol: 'OE', number: '12' },
  },
  {
    label: '藤沢本町',
    line: 'OE',
    name: { kanji: '藤沢本町', hiragana: 'ふじさわほんまち', romaji: 'Fujisawa-hommachi' },
    prev: { kanji: '善行', romaji: 'Zengyo' },
    next: { kanji: '藤沢', romaji: 'Fujisawa' },
    currentNumbering: { symbol: 'OE', number: '12' },
    nextNumbering: { symbol: 'OE', number: '13' },
  },
  {
    label: '藤沢',
    line: 'OE',
    name: { kanji: '藤沢', hiragana: 'ふじさわ', romaji: 'Fujisawa' },
    prev: { kanji: '藤沢本町', romaji: 'Fujisawa-hommachi' },
    next: { kanji: '本鵠沼', romaji: 'Hon-Kugenuma' },
    currentNumbering: { symbol: 'OE', number: '13' },
    nextNumbering: { symbol: 'OE', number: '14' },
  },
  {
    label: '本鵠沼',
    line: 'OE',
    name: { kanji: '本鵠沼', hiragana: 'ほんくげぬま', romaji: 'Hon-Kugenuma' },
    prev: { kanji: '藤沢', romaji: 'Fujisawa' },
    next: { kanji: '鵠沼海岸', romaji: 'Kugenuma-kaigan' },
    currentNumbering: { symbol: 'OE', number: '14' },
    nextNumbering: { symbol: 'OE', number: '15' },
  },
  {
    label: '鵠沼海岸',
    line: 'OE',
    name: { kanji: '鵠沼海岸', hiragana: 'くげぬまかいがん', romaji: 'Kugenuma-kaigan' },
    prev: { kanji: '本鵠沼', romaji: 'Hon-Kugenuma' },
    next: { kanji: '片瀬江ノ島', romaji: 'Katase-Enoshima' },
    currentNumbering: { symbol: 'OE', number: '15' },
    nextNumbering: { symbol: 'OE', number: '16' },
  },
  {
    label: '片瀬江ノ島',
    line: 'OE',
    name: { kanji: '片瀬江ノ島', hiragana: 'かたせえのしま', romaji: 'Katase-Enoshima' },
    prev: { kanji: '', romaji: '' },
    next: { kanji: '鵠沼海岸', romaji: 'Kugenuma-kaigan' },
    currentNumbering: { symbol: 'OE', number: '16' },
    nextNumbering: { symbol: 'OE', number: '15' },
  },
  // --- OT（多摩線）---
  {
    label: '五月台',
    line: 'OT',
    name: { kanji: '五月台', hiragana: 'さつきだい', romaji: 'Satsukidai' },
    prev: { kanji: '新百合ヶ丘', romaji: 'Shin-Yurigaoka' },
    next: { kanji: '栗平', romaji: 'Kurihira' },
    currentNumbering: { symbol: 'OT', number: '01' },
    nextNumbering: { symbol: 'OT', number: '02' },
  },
  {
    label: '栗平',
    line: 'OT',
    name: { kanji: '栗平', hiragana: 'くりひら', romaji: 'Kurihira' },
    prev: { kanji: '五月台', romaji: 'Satsukidai' },
    next: { kanji: '黒川', romaji: 'Kurokawa' },
    currentNumbering: { symbol: 'OT', number: '02' },
    nextNumbering: { symbol: 'OT', number: '03' },
  },
  {
    label: '黒川',
    line: 'OT',
    name: { kanji: '黒川', hiragana: 'くろかわ', romaji: 'Kurokawa' },
    prev: { kanji: '栗平', romaji: 'Kurihira' },
    next: { kanji: 'はるひ野', romaji: 'Haruhino' },
    currentNumbering: { symbol: 'OT', number: '03' },
    nextNumbering: { symbol: 'OT', number: '04' },
  },
  {
    label: 'はるひ野',
    line: 'OT',
    name: { kanji: 'はるひ野', hiragana: 'はるひの', romaji: 'Haruhino' },
    prev: { kanji: '黒川', romaji: 'Kurokawa' },
    next: { kanji: '小田急永山', romaji: 'Odakyu Nagayama' },
    currentNumbering: { symbol: 'OT', number: '04' },
    nextNumbering: { symbol: 'OT', number: '05' },
  },
  {
    label: '小田急永山',
    line: 'OT',
    name: { kanji: '小田急永山', hiragana: 'おだきゅうながやま', romaji: 'Odakyu Nagayama' },
    prev: { kanji: 'はるひ野', romaji: 'Haruhino' },
    next: { kanji: '小田急多摩センター', romaji: 'Odakyu Tama Center' },
    currentNumbering: { symbol: 'OT', number: '05' },
    nextNumbering: { symbol: 'OT', number: '06' },
  },
  {
    label: '小田急多摩センター',
    line: 'OT',
    name: { kanji: '小田急多摩センター', hiragana: 'おだきゅうたまセンター', romaji: 'Odakyu Tama Center' },
    prev: { kanji: '小田急永山', romaji: 'Odakyu Nagayama' },
    next: { kanji: '唐木田', romaji: 'Karakida' },
    currentNumbering: { symbol: 'OT', number: '06' },
    nextNumbering: { symbol: 'OT', number: '07' },
  },
  {
    label: '唐木田',
    line: 'OT',
    name: { kanji: '唐木田', hiragana: 'からきだ', romaji: 'Karakida' },
    prev: { kanji: '', romaji: '' },
    next: { kanji: '小田急多摩センター', romaji: 'Odakyu Tama Center' },
    currentNumbering: { symbol: 'OT', number: '07' },
    nextNumbering: { symbol: 'OT', number: '06' },
  },
];

